server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      # 连接池名称
      pool-name: DataHikariCP
      # 最大连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间
      max-lifetime: 180000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1

mybatis-plus:
  # 指定映射文件位置
#  config-location: classpath:/mapper/*Mapper.xml
  type-aliases-package: top.ctong.server.models.entity

logging:
  level:
    top.ctong.server: debug

jwt:
  token-header: Authorization
  secret: yeb-secret
  expiration: 604800
  token-head: Bearer
  secrete: sadawcas
